// data.dart
const String jsonString = '''
[
  {"habit": "Habit 1", "description": "Description 1 oihoieh oeihpojpoj pojpoj pojpoj pojpoj oeizjdoiez", "gradient": "1", "color1": "#642b73", "color2": "#c6426e", "user": "User 1", "profil": "https://www.missnumerique.com/blog/wp-content/uploads/une-bonne-photo-de-profil-cest-quoi-jurica-koletic.jpg", "comment": "un commentaire peut être beaucoup plus long que la description puisqu'il est en dessous de l'image", "date": "202"},
  {"habit": "Habit 2", "description": "Description 2 iuhiuhiuhiuh", "gradient": "0", "color1": "#f12711", "color2": "#f5af19", "user": "User 2", "profil": "https://www.missnumerique.com/blog/wp-content/uploads/une-bonne-photo-de-profil-cest-quoi-jurica-koletic.jpg", "comment": "un commentaire peut être beaucoup plus long que la description puisqu'il est en dessous de l'image test pour voir si on a bien la taille de la carte qui s'adapte a la longueure de ce texte ou non en sachant que juste en dessous je ne vais rien mettre ijoinorinfozirenfolin", "date": "2022"},
  {"habit": "Habit 3", "description": "Description 3", "gradient": "1", "color1": "#642b73", "color2": "#c6426e", "user": "User 3", "profil": "https://www.missnumerique.com/blog/wp-content/uploads/une-bonne-photo-de-profil-cest-quoi-jurica-koletic.jpg", "comment": "", "date": "Samedi"},
  {"habit": "Habit 4", "description": "Description 4", "gradient": "0", "color1": "#f12711", "color2": "#f5af19", "user": "User 4", "profil": "https://www.missnumerique.com/blog/wp-content/uploads/une-bonne-photo-de-profil-cest-quoi-jurica-koletic.jpg", "comment": "un commentaire peut être beaucoup plus long que la description puisqu'il est en dessous de l'image", "date": "2022 "},
  {"habit": "Habit 5", "description": "Description 5", "gradient": "1", "color1": "#642b73", "color2": "#c6426e", "user": "User 5", "profil": "https://www.missnumerique.com/blog/wp-content/uploads/une-bonne-photo-de-profil-cest-quoi-jurica-koletic.jpg", "comment": "un commentaire peut être beaucoup plus long que la description puisqu'il est en dessous de l'image", "date": "2022 "},
  {"habit": "Habit 6", "description": "Description 6", "gradient": "0", "color1": "#f12711", "color2": "#f5af19", "user": "User 6", "profil": "https://www.missnumerique.com/blog/wp-content/uploads/une-bonne-photo-de-profil-cest-quoi-jurica-koletic.jpg", "comment": "", "date": "2022 "},
  {"habit": "Habit 7", "description": "Description 7", "gradient": "1", "color1": "#642b73", "color2": "#c6426e", "user": "User 7", "profil": "https://www.missnumerique.com/blog/wp-content/uploads/une-bonne-photo-de-profil-cest-quoi-jurica-koletic.jpg", "comment": "un commentaire peut être beaucoup plus long que la description puisqu'il est en dessous de l'image", "date": "2022 "},
  {"habit": "Habit 8", "description": "Description 8", "gradient": "0", "color1": "#f12711", "color2": "#f5af19", "user": "User 8", "profil": "https://www.missnumerique.com/blog/wp-content/uploads/une-bonne-photo-de-profil-cest-quoi-jurica-koletic.jpg", "comment": "", "date": "2022 "},
  {"habit": "Habit 9", "description": "Description 9", "gradient": "1", "color1": "#642b73", "color2": "#c6426e", "user": "User 9", "profil": "https://www.missnumerique.com/blog/wp-content/uploads/une-bonne-photo-de-profil-cest-quoi-jurica-koletic.jpg", "comment": "un commentaire peut être beaucoup plus long que la description puisqu'il est en dessous de l'image", "date": "2022 "}
]
''';
